# documentation: https://docs.crawl4ai.com/
# slogan: Crawl4AI: Open-source LLM Friendly Web Crawler & Scraper.
# tags: webcrawl,llm,webscraping
# port: 11235
# author: @oregapam
# repository: https://github.com/oregapam/awesome-coolify-service-templates

services:
  crawl4ai:
    image: unclecode/crawl4ai
    environment:
      - SERVICE_FQDN_CRAWL4AI_11235
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - GEMINI_API_TOKEN=${GEMINI_API_TOKEN:-}
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s