name: firecrawl
x-common-service:
  image: ghcr.io/mendableai/firecrawl
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  networks:
    - backend
  extra_hosts:
    - 'host.docker.internal:host-gateway'
x-common-env:
  REDIS_URL: '${REDIS_URL:-redis://redis:6379}'
  REDIS_RATE_LIMIT_URL: '${REDIS_URL:-redis://redis:6379}'
  PLAYWRIGHT_MICROSERVICE_URL: '${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000/scrape}'
  USE_DB_AUTHENTICATION: '${USE_DB_AUTHENTICATION:-false}'
  OPENAI_API_KEY: '${OPENAI_API_KEY}'
  OPENAI_BASE_URL: '${OPENAI_BASE_URL:-https://api.openai.com/v1}'
  MODEL_NAME: '${MODEL_NAME:-gpt-4.1-mini}'
  MODEL_EMBEDDING_NAME: '${MODEL_EMBEDDING_NAME}'
  OLLAMA_BASE_URL: '${OLLAMA_BASE_URL}'
  SLACK_WEBHOOK_URL: '${SLACK_WEBHOOK_URL}'
  BULL_AUTH_KEY: '${BULL_AUTH_KEY}'
  TEST_API_KEY: '${TEST_API_KEY}'
  POSTHOG_API_KEY: '${POSTHOG_API_KEY}'
  POSTHOG_HOST: '${POSTHOG_HOST}'
  SUPABASE_ANON_TOKEN: '${SUPABASE_ANON_TOKEN}'
  SUPABASE_URL: '${SUPABASE_URL}'
  SUPABASE_SERVICE_TOKEN: '${SUPABASE_SERVICE_TOKEN}'
  SELF_HOSTED_WEBHOOK_URL: '${SELF_HOSTED_WEBHOOK_URL}'
  SERPER_API_KEY: '${SERPER_API_KEY}'
  SEARCHAPI_API_KEY: '${SEARCHAPI_API_KEY}'
  LOGGING_LEVEL: '${LOGGING_LEVEL}'
  PROXY_SERVER: '${PROXY_SERVER}'
  PROXY_USERNAME: '${PROXY_USERNAME}'
  PROXY_PASSWORD: '${PROXY_PASSWORD}'
  SEARXNG_ENDPOINT: '${SEARXNG_ENDPOINT}'
  SEARXNG_ENGINES: '${SEARXNG_ENGINES}'
  SEARXNG_CATEGORIES: '${SEARXNG_CATEGORIES}'
  MAX_RAM: '${MAX_RAM:-0.95}'
  MAX_CPU: '${MAX_CPU:-0.95}'
services:
  playwright-service:
    image: ghcr.io/mendableai/playwright-service:latest
    environment:
      PORT: 3000
      PROXY_SERVER: '${PROXY_SERVER}'
      PROXY_USERNAME: '${PROXY_USERNAME}'
      PROXY_PASSWORD: '${PROXY_PASSWORD}'
      BLOCK_MEDIA: '${BLOCK_MEDIA}'
    networks:
      - backend
  api:
    image: ghcr.io/mendableai/firecrawl
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      REDIS_URL: '${REDIS_URL:-redis://redis:6379}'
      REDIS_RATE_LIMIT_URL: '${REDIS_URL:-redis://redis:6379}'
      PLAYWRIGHT_MICROSERVICE_URL: '${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000/scrape}'
      USE_DB_AUTHENTICATION: '${USE_DB_AUTHENTICATION:-false}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_BASE_URL: '${OPENAI_BASE_URL:-https://api.openai.com/v1}'
      MODEL_NAME: '${MODEL_NAME:-gpt-4.1-mini}'
      MODEL_EMBEDDING_NAME: '${MODEL_EMBEDDING_NAME}'
      OLLAMA_BASE_URL: '${OLLAMA_BASE_URL}'
      SLACK_WEBHOOK_URL: '${SLACK_WEBHOOK_URL}'
      BULL_AUTH_KEY: '${BULL_AUTH_KEY}'
      TEST_API_KEY: '${TEST_API_KEY}'
      POSTHOG_API_KEY: '${POSTHOG_API_KEY}'
      POSTHOG_HOST: '${POSTHOG_HOST}'
      SUPABASE_ANON_TOKEN: '${SUPABASE_ANON_TOKEN}'
      SUPABASE_URL: '${SUPABASE_URL}'
      SUPABASE_SERVICE_TOKEN: '${SUPABASE_SERVICE_TOKEN}'
      SELF_HOSTED_WEBHOOK_URL: '${SELF_HOSTED_WEBHOOK_URL}'
      SERPER_API_KEY: '${SERPER_API_KEY}'
      SEARCHAPI_API_KEY: '${SEARCHAPI_API_KEY}'
      LOGGING_LEVEL: '${LOGGING_LEVEL}'
      PROXY_SERVER: '${PROXY_SERVER}'
      PROXY_USERNAME: '${PROXY_USERNAME}'
      PROXY_PASSWORD: '${PROXY_PASSWORD}'
      SEARXNG_ENDPOINT: '${SEARXNG_ENDPOINT}'
      SEARXNG_ENGINES: '${SEARXNG_ENGINES}'
      SEARXNG_CATEGORIES: '${SEARXNG_CATEGORIES}'
      HOST: 0.0.0.0
      PORT: '${INTERNAL_PORT:-3002}'
      FLY_PROCESS_GROUP: app
      SERVICE_FQDN_API_3002: '${SERVICE_FQDN_API_3002}'
      MAX_RAM: '${MAX_RAM:-0.95}'
      MAX_CPU: '${MAX_CPU:-0.95}'
    depends_on:
      - redis
      - playwright-service
    command:
      - pnpm
      - run
      - 'start:production'
  worker:
    image: ghcr.io/mendableai/firecrawl
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      REDIS_URL: '${REDIS_URL:-redis://redis:6379}'
      REDIS_RATE_LIMIT_URL: '${REDIS_URL:-redis://redis:6379}'
      PLAYWRIGHT_MICROSERVICE_URL: '${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000/scrape}'
      USE_DB_AUTHENTICATION: '${USE_DB_AUTHENTICATION:-false}'
      OPENAI_API_KEY: '${OPENAI_API_KEY}'
      OPENAI_BASE_URL: '${OPENAI_BASE_URL:-https://api.openai.com/v1}'
      MODEL_NAME: '${MODEL_NAME:-gpt-4.1-mini}'
      MODEL_EMBEDDING_NAME: '${MODEL_EMBEDDING_NAME}'
      OLLAMA_BASE_URL: '${OLLAMA_BASE_URL}'
      SLACK_WEBHOOK_URL: '${SLACK_WEBHOOK_URL}'
      BULL_AUTH_KEY: '${BULL_AUTH_KEY}'
      TEST_API_KEY: '${TEST_API_KEY}'
      POSTHOG_API_KEY: '${POSTHOG_API_KEY}'
      POSTHOG_HOST: '${POSTHOG_HOST}'
      SUPABASE_ANON_TOKEN: '${SUPABASE_ANON_TOKEN}'
      SUPABASE_URL: '${SUPABASE_URL}'
      SUPABASE_SERVICE_TOKEN: '${SUPABASE_SERVICE_TOKEN}'
      SELF_HOSTED_WEBHOOK_URL: '${SELF_HOSTED_WEBHOOK_URL}'
      SERPER_API_KEY: '${SERPER_API_KEY}'
      SEARCHAPI_API_KEY: '${SEARCHAPI_API_KEY}'
      LOGGING_LEVEL: '${LOGGING_LEVEL}'
      PROXY_SERVER: '${PROXY_SERVER}'
      PROXY_USERNAME: '${PROXY_USERNAME}'
      PROXY_PASSWORD: '${PROXY_PASSWORD}'
      SEARXNG_ENDPOINT: '${SEARXNG_ENDPOINT}'
      SEARXNG_ENGINES: '${SEARXNG_ENGINES}'
      SEARXNG_CATEGORIES: '${SEARXNG_CATEGORIES}'
      FLY_PROCESS_GROUP: worker
      MAX_RAM: '${MAX_RAM:-0.95}'
      MAX_CPU: '${MAX_CPU:-0.95}'
    depends_on:
      - redis
      - playwright-service
      - api
    command:
      - pnpm
      - run
      - workers
  redis:
    image: 'redis:alpine'
    networks:
      - backend
    command: 'redis-server --bind 0.0.0.0'
networks:
  backend:
    driver: bridge
