# documentation: https://github.com/androidseb25/iGotify-Notification-Assistent
# slogan: Docker container for sending Gotify notifications to iOS devices (bridge to gotify websocket)
# tags: gotify, igotify, notifications, ios, bridge
# port: 80;8080
# author: @oregapam
# repository: https://github.com/oregapam/awesome-coolify-service-templates

services:
  gotify:
    image: gotify/server
    security_opt:
      - no-new-privileges:true
    environment:
      - SERVICE_URL_GOTIFY_80
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_USERNAME:-admin}
      - GOTIFY_DEFAULTUSER_PASS=${SERVICE_PASSWORD_GOTIFY}
      - GOTIFY_DATABASE_DIALECT=${GOTIFY_DATABASE_DIALECT:-sqlite3}
      - GOTIFY_DATABASE_CONNECTION=${GOTIFY_DATABASE_CONNECTION:-data/gotify.db}
      - GOTIFY_PASSSTRENGTH=${GOTIFY_PASSSTRENGTH:-10}
      - GOTIFY_UPLOADEDIMAGESDIR=${GOTIFY_UPLOADEDIMAGESDIR:-data/images}
      - GOTIFY_PLUGINSDIR=${GOTIFY_PLUGINSDIR:-data/plugins}
      - GOTIFY_SERVER_PORT=${GOTIFY_SERVER_PORT:-80}
      - GOTIFY_REGISTRATION=${GOTIFY_REGISTRATION:-false}
    volumes:
      - 'gotify-data:/app/data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/health"]
      interval: 5s
      timeout: 20s
      retries: 10

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/Version" ]
      interval: "3s"
      timeout: "3s"
      retries: 5
    environment:
      - SERVICE_URL_IGOTIFY_8080
    volumes:
      - api-data:/app/data
volumes:
  gotify-data:
  api-data: