# documentation: https://docs.linkwarden.app/
# slogan: Self-hosted collaborative bookmark manager to collect, organize, and preserve webpages, articles, and documents.
# tags: bookmarks,web,archive,selfhosted,productivity
# port: 3000
# author: @oregapam
# repository: https://github.com/oregapam/awesome-coolify-service-templates

services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-linkwarden}'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  linkwarden:
    environment:
      - SERVICE_FQDN_LINKWARDEN_3000
      - NEXTAUTH_URL=$SERVICE_URL_LINKWARDEN/api/v1/auth
      - 'NEXTAUTH_SECRET=${SERVICE_PASSWORD_NEXTAUTH}'
      - 'DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-linkwarden}'
      - 'NEXT_PUBLIC_DISABLE_REGISTRATION=${NEXT_PUBLIC_DISABLE_REGISTRATION:-false}'
    restart: always
    image: 'ghcr.io/linkwarden/linkwarden:latest'
    volumes:
      - 'linkwarden_data:/data/data'
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: 'getmeili/meilisearch:v1.12.8'
    restart: always
    volumes:
      - 'meili_data:/meili_data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:7700/health'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
volumes:
  pgdata:
  linkwarden_data:
  meili_data: