# documentation: https://pocket-id.org/docs/
# slogan: A simple and easy-to-use OIDC provider that allows users to authenticate with their passkeys to your services.
# tags: web,api,oidc,authentication,passkeys
# port: 1411
# author: @oregapam
# repository: https://github.com/oregapam/awesome-coolify-service-templates

services:
  pocketid:
    image: ghcr.io/pocket-id/pocket-id
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_POCKETID_1411
      - APP_URL=$SERVICE_FQDN_POCKETID
      - TRUST_PROXY=${TRUST_PROXY:-true}
      - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - DB_PROVIDER=${DB_PROVIDER:-postgres}
      - 'DB_CONNECTION_STRING=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB}'
    volumes:
      - "./data:/app/data"
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-pocketid}'
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10