# documentation: https://docs.twenty.com/developers/self-host/self-host
# slogan: Building a modern alternative to Salesforce, powered by the community.
# tags: crm,customer-relationship-management,saas,productivity,open-source
# port: 3000
# author: @oregapam
# repository: https://github.com/oregapam/awesome-coolify-service-templates

name: twenty

services:
  server:
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    environment:
      - SERVICE_FQDN_SERVER_3000
      - NODE_PORT=3000
      - PG_DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-twentycrm}
      - SERVER_URL=${SERVICE_URL_SERVER}
      - FRONTEND_URL=${SERVICE_URL_SERVER}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DISABLE_DB_MIGRATIONS=${DISABLE_DB_MIGRATIONS}
      - DISABLE_CRON_JOBS_REGISTRATION=${DISABLE_CRON_JOBS_REGISTRATION}
      - APP_SECRET=${SERVICE_PASSWORD_SECRET}
      - IS_CONFIG_VARIABLES_IN_DB_ENABLED=${IS_CONFIG_VARIABLES_IN_DB_ENABLED:-true}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthz
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  worker:
    image: twentycrm/twenty:latest
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]
    environment:
      - PG_DATABASE_URL=postgresql://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-twentycrm}
      - SERVER_URL=${SERVICE_URL_SERVER}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DISABLE_DB_MIGRATIONS=${DISABLE_DB_MIGRATIONS:-true}
      - DISABLE_CRON_JOBS_REGISTRATION=${DISABLE_CRON_JOBS_REGISTRATION:-true}
      - APP_SECRET=${SERVICE_PASSWORD_SECRET}
      - IS_CONFIG_VARIABLES_IN_DB_ENABLED=${IS_CONFIG_VARIABLES_IN_DB_ENABLED:-true}

    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_healthy
    restart: always

  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-twentycrm}'
    restart: always
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: redis
    restart: always
    command: ["--maxmemory-policy", "noeviction"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
  server-local-data: